proposal_geojson_path: ./data/xn77hbrh_xn77j018_osm.geojson  # Put your own file here.
ground_truth:
  !Osm
    bounding_box:
      left_lon: 139.788745
      right_lon: 139.792244
      bottom_lat: 35.683695
      top_lat: 35.685717
data_dir: ./data