proposal_geofile_path: ./data/ground_truth.geojson  # Put your own file here.
ground_truth:
  !Geofile
    filepath: ./data/ground_truth.geojson
  # !Osm
  #   bounding_box: # small area of downtown Tokyo
  #     left_lon: 139.780237100
  #     right_lon: 139.784625728
  #     bottom_lat: 35.673094145
  #     top_lat: 35.677518721
  # !Osm
  #   bounding_box: # ~46 square km of downtown Tokyo
  #     left_lon: 139.77451342
  #     right_lon: 139.850199790
  #     bottom_lat: 35.650358475
  #     top_lat: 35.71006819
topo_params:
  resampling_distance: 11.0
  hole_radius: 6.0
data_dir: ./data