name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install GDAL
      run: sudo apt update && sudo apt -y install libgdal30=3.4.1+dfsg-1build4 libgdal-dev=3.4.1+dfsg-1build4
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
