name: Rust CI & CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install GDAL
      run: sudo apt update && sudo apt -y install libgdal30=3.4.1+dfsg-1build4 libgdal-dev=3.4.1+dfsg-1build4
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test

  build-and-push-image:
    needs: build
    runs-on: ubuntu-22.04

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: balazsopra/topo-rust:latest