name: Rust CI & CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test-and-push-image:
    runs-on: ubuntu-22.04

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build tester image - run tests
      uses: docker/build-push-action@v4
      with:
        platforms: linux/amd64
        tags: topo-rust-tester:latest
        load: true
        target: tester
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push release image
      uses: docker/build-push-action@v4
      with:
        platforms: linux/amd64
        push: true
        tags: balazsopra/topo-rust:${{ steps.date.outputs.date }}.${{ github.sha }}